#!/usr/local/cpanel/3rdparty/bin/perl
# cpanel - find-latest-version                  Copyright(c) 2019 cPanel, L.L.C.
#                                                           All rights Reserved.
# copyright@cpanel.net                                         http://cpanel.net
# This code is subject to the cPanel license. Unauthorized copying is prohibited

package ea_rubygem_nokogiri::find_latest_version;

use strict;
use warnings;

use FindBin;
use lib "../ea-tools/lib/ea4_tool";    # assumes ea-tools is checked out next to this repo
use ea4_tool::util ();

my $release;

ea4_tool::util::find_latest_version( \&_get_required, \&_add_sum ) if !caller();

###############
#### helpers ##
###############

sub _get_required {
    my ($http) = @_;

    $release = ea4_tool::util::get_rubygem_newest_release( $http, gem => "nokogiri", ruby => "2.7" );

    return @{$release}{qw(version url name)};
}

sub _add_sum {
    my ( $http, $hr ) = @_;

    $hr->{tarball}{sum} = { hex => $release->{sha256}, type => "sha256" };

    return 1;
}
